### PR TITLE
Rewrite npm On-Site server requirements

### LINKED ISSUE #510: New content for On-Site server requirements
Should focus on (and clearly list) minimal specs for a server intended to run an instance of npm On-Site, including:

- supported platforms/systems
- architecture
- minimum kernel version
- minimum RAM
- minimum disk space
- ports that must be open for inbound TCP traffic

Should probably leave details of Node/npm install to the quickstart/installation guide, since that can be considered part of the installation, and we may eventually have `apt-get` or `yum` based installs that would not require Node/npm to be pre-installed.

Should also include notes on AWS setup.

### PR DESCRIPTION
**Pull request by nexdrew**
Fixes #510. New content based on [this gist](https://gist.github.com/nexdrew/db6d799f85ff62c348b1) as part of our focus on the "first 10 minute UX".

Content change only. Does not include any changes to URLs, page titles, or nav items.

### CODE REVIEW

**Comment by nexdrew** [comment]
cc @bcoe

**Comment by ashleygwilliams** [comment]
can you review @bcoe? once it's :ok: i'll merge

**Comment by bcoe** [comment]
:shipit:

**Comment by ashleygwilliams** [comment]
merging!

**Pull request merged**
