### PR TITLE
More love for On-Site requirements

### PR DESCRIPTION
**Pull request by nexdrew**
- Add the 8082 port (for auth endpoints)
- Better description for ports required
- Add sample AWS Security Group settings (image)
- Add requirement for access to the public internet (to download keys, dependencies, and containers)
- Add link to `npmo-installer` repo, where comments on issues could be helpful to customers

### CODE REVIEW

**Comment by nexdrew** [comment]
cc @bcoe

**Comment by bcoe** [comment]
@nexdrew this is looking good -- we don't actually need `5005` open so it might be good to clip this line out.

**Comment by nexdrew** [comment]
Ok will do

**Comment by nexdrew** [comment]
@bcoe Updated the screenshot. Let me know what you think.

**Comment by bcoe** [comment]
:shipit: you rock.

**Pull request merged**
