### PR TITLE
remove faq page from docs site

### PR DESCRIPTION
**Pull request by ashleygwilliams**
this page is toxic and adds no value.

### CODE REVIEW

**Comment by rod11** [comment]
Can we add some kind of non-toxic version later?   FAQs are often good ... even if this one is evil.

**Comment by ashleygwilliams** [comment]
@rod11 no. i do not think that long form guides have any place in the cli docs and the release cycle means that updating them takes an extremely long time.

frankly faqs in technical documentation aren't great anyways as they completely destroy context. i think we can cover the material that was "covered" in the faq with new docs that will be both more helpful and less aggressive.

**Comment by rod11** [comment]
Hey @ashleygwilliams - Could you help me understand the full vision here?

Is the aim to do the following?

1. Better technical docs that are not structured like "aggressive" man pages
2. How to Guides elsewhere ... not in docs
3. FAQ pages elsewhere ... not in docs

Not sure if you feel the last one is not a good idea.

**Comment by ashleygwilliams** [comment]
closing in favor of simply removing the page altogether.

**Pull request closed without merging**
