### PR TITLE
doc: Convert typewriter apostrophes to typographic apostrophes

### PR DESCRIPTION
**Pull request by jonathanp**
Related to https://github.com/npm/npm/pull/10682 :)

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey! looks like travis failed on 0.10. might've been a fluke (has happened to me before). i restarted the test, so let's wait and see.

**Comment by jonathanp** [comment]
Yep, the travis fail is unrelated to this commit since it does not contain any code. :)

**Comment by ashleygwilliams** [comment]
would you mind rebasing? then travis will pass (i know it doesn't matter but....)

**Comment by jonathanp** [comment]
Np, rebased now!

**Comment by jonathanp** [comment]
What's the status on this @ashleygwilliams? :)

**Comment by ashleygwilliams** [comment]
hey @jonathanp i'm waiting to merge a couple things, and then if you could rebase/fix those that would be amazing! thanks so much

**Comment by ashleygwilliams** [comment]
hi @jonathanp do you think you'll be able to rebase this? let me know!

**Pull request closed without merging**
