### PR TITLE
fix instance of tl;dr in COC

### PR DESCRIPTION
**Pull request by Charlotteis**
Following on from #775.

Changes 'tl;dr' in the Code of Conduct to 'In Summary'. I felt this was better than 'Quick Summary' for a COC because I don't want your reading of a COC to be quick or haphazard.

With https://github.com/npm/docs/pull/775#issuecomment-263793149 in mind, let's discuss this!

🌟 Have a lovely day 🌟

### CODE REVIEW

**Comment by Charlotteis** [comment]
PS Sorry for the bad branching name, I was editing from the browser (yaaaaay for lower barriers to contributing!) and forgot to create my own branch, so GitHub did it for me.

**Comment by ashleygwilliams** [comment]
i like it! thank you for this!

**Comment by ashleygwilliams** [comment]
p.s. super no worries on the branch name.

**Comment by Charlotteis** [comment]
MY FIRST NPM CONTRIBUTION
WOOOOO
Ta AG

**Pull request merged**
