### PR TITLE
Modify the previous command line

### PR DESCRIPTION
**Pull request by lushen**
the original command line does not make sense when you run it. If you want to ls all the files or directory inside lodash, you should get in it at first. I just think "ls node_modules" is not easy to understand for npm novice.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hi @lushen thanks for contributing. i'm not sure i understand the confusion you are talking about here. `ls node_modules` will run an `ls` inside the `node_modules` directory. our goal here is to show that `lodash` was installed by showing the `lodash` directory inside the `node_modules` directory. this does that. 

piping is a significantly more advanced shell concept than the `ls` command. in what way do you believe the command you provided is easier for beginners?

**Comment by ashleygwilliams** [comment]
also, it turns out what you suggested doesn't work. instead of `ls node_modules` it just does `ls` on the current directory. see:

```
(jessie)ag_dubs@localhost:~/Projects/mansplain$ cd node_modules/ | ls
index.js  LICENSE  man-explain.png  node_modules  package.json  README.md  test
```

closing.

**Comment by lushen** [comment]
I mean if just give ` ls node_modules`, for me, I will just copy and run it in my terminal. However, it does not fulfill my propose. Or you just say "run an `ls` inside the 'node_modules' directory, which will be much better.

**Comment by ashleygwilliams** [comment]
i'm afraid we are going to have to agree to disagree. the npm docs do assume some knowledge of your shell, and so i think this is sufficient.

HOWEVER, you have pointed out that this is not a windows friendly one. so thank you!

**Comment by lushen** [comment]
OK, maybe I am not a native speaker. I just treat `ls` as a real command line instead of its meaning based on the context.

**Comment by ashleygwilliams** [comment]
hi! i definitely am interested in making the docs friendly to non-native speakers! i am using the `ls` command as the command in this example. could you be clearer about your confusion.

on my end, we want you (at a linux terminal) to type (or cut and paste):

```
ls node_modules
```

we expect you to see

```
lodash
```

which represents the lodash module

**Pull request closed without merging**
