### PR TITLE
feat: rebranding from npm On-Site to npm Enterprise

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
noted. will merge and push to prod when passing, @bcoe

**Comment by ashleygwilliams** [comment]
plz squash into one commit thx :)

**Comment by bcoe** [comment]
squashed 👍

**Comment by nexdrew** [comment]
CI is green, staging deployment looks good. Gonna merge and promote to production.

**Comment by nexdrew** [comment]
Successfully deployed to production \o/

**Pull request merged**
