### PR TITLE
adhere to padded-blocks

### PR DESCRIPTION
**Pull request by LinusU**
We are in the process of adding back the rule `padded-blocks` into `standard`. It was temporarily disabled because of a bug in eslint which now has been fixed.

This pull request makes sure that your coding style is compliant with the new version.

Please see feross/standard#170 for more info.

### CODE REVIEW

**Comment by zeke** [comment]
:+1:

**Comment by LinusU** [comment]
@zeke Could this get merged? Who should I ping?

**Comment by zeke** [comment]
@LinusU I don't know, honesty.

@linclark and I used to maintain this repo, but we no longer have commit bit.

**Comment by LinusU** [comment]
@rockbot I saw that you merged some pull requests recently, can you take a look at this?

**Comment by ashleygwilliams** [comment]
hi @LinusU ! i am the new docs person! could you rebase on master please? otherwise looks good to me

**Comment by LinusU** [comment]
@ashleygwilliams Done :+1:

**Comment by ashleygwilliams** [comment]
c82699127b46acbca7e0047e5aa3061fe4a77fcd

**Pull request closed without merging**
