### PR TITLE
fixes docs to be more print-friendly (#697)

### LINKED ISSUE #697: The documentation is not print-friendly
# Print view
- "What is npm?" (one section - https://docs.npmjs.com/getting-started/what-is-npm)

image
- "All Docs" (all sections - https://docs.npmjs.com/all)

image
## Proposal

[CSS3 @media print rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) can be used in order to hide certain elements and to position others adequate.

For example:
- hide all videos
- on the page "All Docs'(all sections listed), show table of contents. (inspire from: https://nodejs.org/api/all.html)
- on "one section" pages("What is npm?"), obove the title, add: **previous section name(if exists) > current section name > next section name(if exists)**
  and above these, add the parent section name (example: print-friendly_one_section_pages)

### PR DESCRIPTION
**Pull request by kellyjandrews**
Cleans up print version of documentation (
- removes videos
- removes navigation, 
- adjusts font-sizes
- adds section titles and breadcrumbs
- adds toc to all docs page

Fixes #697

### CODE REVIEW

**Comment by kellyjandrews** [comment]
Taking a look at this.

**Comment by kellyjandrews** [comment]
When I run `npm run test` it passes.  Is there something I missed here?

**Comment by kellyjandrews** [comment]
@ashleygwilliams - does this look reasonable to you?

**Comment by ashleygwilliams** [comment]
hey @kellyjandrews this is awesome! (sorry for the delay in review) locally i'm seeing this now, does this look right to you? if so i will merge :) 
screen shot 2016-07-05 at 12 35 23 pm

**Comment by kellyjandrews** [comment]
@ashleygwilliams lgtm

Let me know if there are any other issues.

**Comment by kellyjandrews** [comment]
YAY!

**Pull request merged**
