### PR TITLE
Update NPM_CONFIG_PREFIX env variable to lowercase

### PR DESCRIPTION
**Pull request by tuhoojabotti**
Using npm@3.10.3, the NPM_CONFIG_PREFIX env variable has no effect, but in lowercase it works. Running in Docker Node.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hi @tuhoojabotti - thanks for this! since our docs are neither npm version nor platform specific, i'll need to make sure that this change works on all the other platforms as well. i'll let you know!

**Comment by ashleygwilliams** [comment]
cc @zkat @iarna any thoughts on this having changed? was it wrong to begin with? is the need for lower case platform specific?

**Comment by tuhoojabotti** [comment]
I don't know if/when it has changed to lower case, but I noted that all npm environment variables tend to be in lowercase elsewhere. For example: https://docs.npmjs.com/misc/config#environment-variables

**Comment by ashleygwilliams** [comment]
hey actually @tuhoojabotti now that you mention it, this doc actually lives in the cli codebase, so you'd want to make the PR over on `npm/npm`. https://github.com/npm/npm/blob/latest/doc/misc/npm-config.md#environment-variables

feel free to ping me if you run into any issues. closing for now!

**Comment by tuhoojabotti** [comment]
@ashleygwilliams I researched the issue some more and opened an issue on the npm cli: https://github.com/npm/npm/issues/14528

**Comment by ashleygwilliams** [comment]
awesome! thanks so much @tuhoojabotti

**Pull request closed without merging**
