### PR TITLE
replacing hgroup with header tags

### PR DESCRIPTION
**Pull request by lrlna**
Substituting deprecated hgroup tag ^.^. Closing #137

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
yayayay irena!!!

**Comment by lrlna** [comment]
hehehe thanks myles!!

**Comment by ashleygwilliams** [comment]
thanks so much but #385 was in first! watch the `your-first-pr` label for more great issues! <3

**Comment by lrlna** [comment]
<3 < 3 <3

**Pull request closed without merging**
