### PR TITLE
New npm On-Site Quickstart guide

### PR DESCRIPTION
**Pull request by nexdrew**
First incremental change at making the On-Site docs More Better™ - with a focus on streamlining the first 10 minute experience.

Content change only - no additional menu items, URLs, or anything - based on this gist: https://gist.github.com/nexdrew/b49d0ad2925e7859260d

There are currently no tests for On-Site content, and this PR does not add any.

Feedback is welcomed!

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
this looks awesome. thanks for doing this!

could you rebase to edit your commit message to be active present tense? e.g. "rewrite npmO quickstart"

then i'll merge!

**Comment by nexdrew** [comment]
Commit message change forthcoming...

**Comment by nexdrew** [comment]
Commit message changed.

**Comment by ashleygwilliams** [comment]
looks great. merging.

**Pull request merged**
