### PR TITLE
Change some the http links to https

### PR DESCRIPTION
**Pull request by vramana**

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
could you rebase? then i'll merge. sorry for the delay in response.

**Comment by vramana** [comment]
Sure.

**Comment by ashleygwilliams** [comment]
hey @vramana were you gonna rebase?

**Comment by vramana** [comment]
@ashleygwilliams Done! Sorry for the delay.

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/docs/pull/545

**Pull request closed without merging**
